feat: implement parser
Webserver-42/webserv pull request #2
Opened 2023-04-12 12:57 UTC by rladjswkd

configuration file parser 구현입니다.
구현한 기능들은 WebServer Project에서 ConfigParser 클래스 구현 아이템 내에 체크 박스에 표시해 뒀습니다.

2023-04-12 13:08 UTC, rladjswkd commented
- 기본 값을 활용할지, 필수 입력 지시자들을 정할지 결정한 후 필수 입력 지시자들을 정한 경우, 각 블록에 필수 지시자들이 모두 포함되었는지 확인하고 그렇지 않다면 예외 처리하기

- Config 객체에 ConfigServer를 추가할 때, host, port는 ServerMap의 키로만 활용하고, ConfigServer 객체 내에 멤버로는 저장하지 않게 수정하기.

- Config 객체에 ConfigServer를 추가할 때, serverName은 ServerSubMap의 키로만 활용하고, ConfigServer 객체 내에 멤버로는 저장하지 않게 수정하기.

- std::map은 정렬 방식에 따라 서버가 저장되는 순서가 입력 순서가 아니므로 default server 설정하기. 별도의 클래스를 생성해 ServerSubMap 대신 ServerMap의 키로 활용하고, 그 안에 멤버는 default server와 serverSubMap을 갖게 구현하기.

2023-04-14 07:21 UTC, rladjswkd commented
- [ ] 기본값을 활용하게 구현하기   

  |  | 기본값 | configuration 파일에 지시자가 없을 때 처리 방법|
  |--- | --- | ---|
  |listen | *:8000 | 기본값 설정|
  |server_name | “” | 기본값 설정|
  |error_page | default page files | 기본값 설정|
  |client_max_body_size | 1000000 | 기본값 설정|
  |limit_except | - | 무시|
  |redirect | - | 무시|
  |alias | - | 무시|
  |autoindex | off | 기본값 설정|
  |index | index.html | 기본값 설정|   

- [ ] listen 지시자의 host 부분에 * 뿐만 아니라 localhost도 처리할 수 있도록 구현하기.
- [ ] error_page 지시자를 담는 구조를 key는 error code, value는 page로 하는 std::map 구조로 수정하고 error code에 해당하는 page를 출력하게 구현하기. configuration file에 선언되지 않은 error code에 대해선 해당하는 기본 페이지 경로를 매크로로 정의해 해당 경로를 활용하기.
- [ ] Config 객체를 생성한 후, ConfigServer가 가질 수 있는 지시자들 중 값이 비어있는 것들을 Config level의 지시자들로 채워넣을 수 있는 것들을 채워넣는 기능, 마찬가지로 ConfigLocation이 가질 수 있는 지시자들 중 값이 비어있는 것들을 ConfigServer level의 지시자들로 채워넣을 수 있는 것들을 채워넣는 기능 구현하기.

2023-04-17 06:13 UTC, sweetykr7 approved these changes
확인 완료하였습니다!! 방대한 코드 작성하시느라 수고 많으셨습니다~!!

2023-04-18 08:22 UTC, sweetykr7 approved these changes
확인 완료하였습니다!

2023-04-18 10:51 UTC, rladjswkd commented
- [ ] `clientMaxBodySize`, `autoIndex`의 타입을 각각 `size_t`, `bool`로 변경

2023-04-19 04:41 UTC, Eingerjar requested changes
Block.cpp 부탁드리겠습니다!!

2023-04-19 04:41 UTC, Eingerjar commented on Block.hpp
> +	bool			autoIndex;
회의때 이야기 했던 clientMaxBodySize와 autoIndex 타입변경 수정사항 확인했습니다

2023-04-19 04:41 UTC, Eingerjar commented on Block.cpp
> +	if (!(mask & AUTOINDEX_BIT))#include "Block.hpp"
이 부분부터 수정하시다가 섞인 것 같습니다.

2023-04-19 04:57 UTC, Eingerjar approved these changes
변경사항 확인했습니다!

2023-04-19 04:58 UTC, sweetykr7 approved these changes
수고하셨습니다!!!

2023-04-19 04:58 UTC, merged