fix: child exit and responseCGI exception
Webserver-42/webserv pull request #47
Opened 2023-05-23 06:37 UTC by Eingerjar

RequestHandler 예외 처리

2023-05-23 07:51 UTC, rladjswkd approved these changes
확인했습니다 나중에 #48이랑 충돌나는 부분 해결하겠습니다

2023-05-23 11:42 UTC, rladjswkd requested changes
- [ ] 디렉터리 경로를 config에서 찾을 수 없을 때나 찾을 수 있더라도 실제로 존재하지 않을 때 응답 상태 코드 404
- [x] 경로로 uri가 전달됐고 인덱스가 지정됐지만 인덱스를 찾을 수 없을 때 403
- [ ] 디렉터리 경로와 인덱스가 모두 존재하지만 경로 상 하나라도 접근 권한이 없으면 500
- [ ] limit_except로 제외한 메서드로 접근할 때 403
- [ ] 서버가 서버 방침 상 막을 메서드로 접근할 때 405

2023-05-24 12:09 UTC, rladjswkd approved these changes

2023-05-24 12:10 UTC, sweetykr7 approved these changes
확인하였습니다!!

2023-05-24 12:10 UTC, merged